### ISSUE TITLE
Put a link in the readme/description

### ISSUE THREAD

**Issue by pfirsich** [josh-perry/periodic-table-of-projects#1]
Yo josh, I saw this on my feed and there was no link to GitHub pages, so I had to lift my left hand and move it (along with my right hand) to the keyboard to enter the URL myself: https://josh-perry.github.io/periodic-table-of-projects/
I am livid and exhausted. I expect full compensation for the effort in Bitcoin.

**Comment by josh-perry** [comment]
Partially fixed, no Bitcoin will be transferred.

**Comment by pfirsich** [comment]
I am willing to accept your firstborn son instead to raise as my own and have rule over my dominion after I have passed.
